# Demographic Survey Data #

----Load in Demographic Survey Data---

Import pandas as pd

In [14]:
import pandas as pd

Import Data File

In [15]:
df = pd.read_csv('/Users/paulpacheco/Desktop/Test Data Files/demographicsurvey_survey_demographics_2203041344.csv')
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_column', 100)
df

,date,time,group,subject,session,build,gender_response,gender_latency,genderother_response,genderother_latency,age_response,age_latency,ethnicity_response,ethnicity_latency,raceoriginoption1_response,raceoriginoption1_latency,raceoriginoption2_response,raceoriginoption2_latency,raceoriginoption3_response,raceoriginoption3_latency,raceoriginoption4_response,raceoriginoption4_latency,raceoriginoption5_response,raceoriginoption5_latency,raceoriginoption6_response,raceoriginoption6_latency,raceoriginoption7_response,raceoriginoption7_latency,raceoriginoption8_response,raceoriginoption8_latency,raceoriginoption9_response,raceoriginoption9_latency,raceoriginoption10_response,raceoriginoption10_latency,raceoriginoption11_response,raceoriginoption11_latency,raceoriginoption12_response,raceoriginoption12_latency,raceoriginoption13_response,raceoriginoption13_latency,raceoriginother_response,raceoriginother_latency,highest_level_of_education_response,highest_level_of_education_latency,highest_level_of_educationother_response,highest_level_of_educationother_latency,year_in_College_response,year_in_College_latency,major_response,major_latency,majorother_response,majorother_latency,household_education_response,household_education_latency,homeownership_response,homeownership_latency,rooms_in_house_response,rooms_in_house_latency,region_of_us_response,region_of_us_latency,region_of_usother_response,region_of_usother_latency,Unnamed: 62
0,2022-01-27,13:14:00,2,23140554,1,6.5.2,Female,4632,NaN,4632,21,4632,"Hispanic or Latino (a person of Cuban, Mexican...",3009,NaN,3167,NaN,3167,NaN,3167,NaN,3167,NaN,3167,NaN,3167,NaN,3167,NaN,3167,NaN,3167,NaN,3167,White,3167,NaN,3167,NaN,3167,NaN,3167,"Some college, no degree",1244,NaN,1244,Four Years,5304,Humanities / Arts,23397,NaN,23397,Four Year Degree,2831,yes,2831,9,2831,"Pacific (Washington, Oregon, California, Alask...",10133,NaN,10133,NaN
1,2022-01-27,14:14:46,1,664692613,1,6.5.2,Female,7921,NaN,7921,18,7921,Not Hispanic or Latino),5793,NaN,6414,NaN,6414,NaN,6414,NaN,6414,NaN,6414,NaN,6414,NaN,6414,NaN,6414,NaN,6414,NaN,6414,White,6414,NaN,6414,NaN,6414,NaN,6414,"Some college, no degree",7484,NaN,7484,First Year,6383,Social Science,12415,NaN,12415,Some Graduate School,33234,yes,33234,11+,33234,"New England (Maine, New Hampshire, Vermont, Ma...",6141,NaN,6141,NaN
2,2022-02-02,14:21:30,2,599191245,1,6.5.2,Gender Variant/Non-Conforming,5472,NaN,5472,21,5472,Not Hispanic or Latino),3812,NaN,3210,NaN,3210,NaN,3210,NaN,3210,NaN,3210,NaN,3210,NaN,3210,NaN,3210,NaN,3210,NaN,3210,White,3210,NaN,3210,NaN,3210,NaN,3210,"Some college, no degree",6824,NaN,6824,Third Year,4173,Social Science,7372,NaN,7372,Four Year Degree,18435,no,18435,6,18435,"New England (Maine, New Hampshire, Vermont, Ma...",2420,NaN,2420,NaN
3,2022-02-03,13:21:34,2,481626968,1,6.5.2,Male,4529,NaN,4529,21,4529,Not Hispanic or Latino),4834,NaN,5054,NaN,5054,NaN,5054,NaN,5054,NaN,5054,NaN,5054,NaN,5054,NaN,5054,NaN,5054,NaN,5054,White,5054,NaN,5054,NaN,5054,NaN,5054,"Some college, no degree",6281,NaN,6281,Third Year,5418,Chemistry / Biochemistry,6838,NaN,6838,Four Year Degree,43177,no,43177,5,43177,"Middle Atlantic (New York, New Jersey, Pennsyl...",5861,NaN,5861,NaN
4,2022-02-08,14:18:07,2,299228195,1,6.5.2,Female,7951,NaN,7951,18,7951,Not Hispanic or Latino),7429,NaN,6968,NaN,6968,NaN,6968,NaN,6968,NaN,6968,NaN,6968,NaN,6968,NaN,6968,NaN,6968,NaN,6968,White,6968,NaN,6968,NaN,6968,NaN,6968,"Some college, no degree",9635,NaN,9635,First Year,5270,Social Science,10780,NaN,10780,Master's Degree,51609,no,51609,11+,51609,"New England (Maine, New Hampshire, Vermont, Ma...",7717,NaN,7717,NaN
5,2022-02-15,14:36:47,1,464449427,1,6.5.2,Female,5330,NaN,5330,18,5330,I prefer not to answer this question,2497,NaN,4107,NaN,4107,NaN,4107,NaN,4107,NaN,4107,NaN,4107,NaN,4107,NaN,4107,NaN,4107,NaN,4107,NaN,4107,I prefer not to answer this question,4107,NaN,4107,NaN,4107,"Some college, no degree",14325,NaN,14325,First Year,3816,Chemical Engineering,5708,NaN,5708,Master's Degree,48303,yes,48303,11+,48303,"New England (Maine, New Hampshire, Vermont, Ma...",3882,NaN,3882,NaN
6,2022-02-18,16:29:41,1,828122693,1,6.5.2,Male,5284,NaN,5284,20,5284,Not Hispanic or Latino),3017,NaN,6196,NaN,6196,NaN,6196,NaN,6196,NaN,6196,NaN,6196,NaN,6196,NaN,6196,NaN,6196,Middle Eastern or North African,6196,White,6196,NaN,6196,NaN,6196,NaN,6196,"Some college, no degree",3641,NaN,3641,Third Year,9030,Biology / Biotechnology,4473,NaN,4473,Some High School,41143,yes,41143,10,41143,"New England (Maine, New Hampshire, Vermont, Ma...",7324,NaN,7324,NaN
7,2022-02-22,12:29:56,2,835352491,1,6.5.2,Male,8627,NaN,8627,21,8627,Not Hispanic or Latino),11107,NaN,17944,NaN,17944,NaN,17944,NaN,17944,West Asian,17944,NaN,17944,NaN,17944,NaN,17944,NaN,17944,NaN,17944,White,17944,NaN,17944,NaN,17944,NaN,17944,"Some college, no degree",10441,NaN,10441,Third Year,4994,Other (please specify):,20226,Management Engineering,20226,Four Year Degree,27947,yes,27947,9,27947,"New England (Maine, New Hampshire, Vermont, Ma...",5539,NaN,5539,NaN
8,2022-02-24,13:54:53,1,956226984,1,6.5.2,Female,5725,NaN,5725,18,5725,Not Hispanic or Latino),4072,NaN,4945,NaN,4945,NaN,4945,NaN,4945,NaN,4945,NaN,4945,NaN,4945,NaN,4945,NaN,4945,NaN,4945,White,4945,NaN,4945,NaN,4945,NaN,4945,High school diploma or equivalent,6508,NaN,6508,First Year,3643,Social Science,8542,NaN,8542,Four Year Degree,39130,yes,39130,3,39130,"New England (Maine, New Hampshire, Vermont, Ma...",6113,NaN,6113,NaN
9,2022-03-02,13:46:25,1,325562366,1,6.5.2,Male,5468,NaN,5468,21,5468,"Hispanic or Latino (a person of Cuban, Mexican...",5601,NaN,5697,NaN,5697,NaN,5697,NaN,5697,NaN,5697,NaN,5697,NaN,5697,NaN,5697,NaN,5697,NaN,5697,White,5697,NaN,5697,NaN,5697,NaN,5697,"Some college, no degree",13822,NaN,13822,Four Years,9180,Mechanical / Materials Engineering,9873,NaN,9873,Four Year Degree,15266,yes,15266,3,15266,I lived outside the United States (please spec...,12532,Dominican Republic,12532,NaN

Filter colomns by the headers you would like

In [16]:
df=df[['subject','group','gender_response','genderother_response','age_response','ethnicity_response','raceoriginoption1_response','raceoriginoption2_response','raceoriginoption3_response','raceoriginoption4_response','raceoriginoption5_response','raceoriginoption6_response','raceoriginoption7_response','raceoriginoption8_response','raceoriginoption9_response','raceoriginoption10_response','raceoriginoption11_response','raceoriginoption12_response','raceoriginoption13_response','raceoriginother_response','highest_level_of_education_response','highest_level_of_educationother_response','year_in_College_response','major_response','household_education_response','homeownership_response','rooms_in_house_response','region_of_us_response','region_of_usother_response']]
df

,subject,group,gender_response,genderother_response,age_response,ethnicity_response,raceoriginoption1_response,raceoriginoption2_response,raceoriginoption3_response,raceoriginoption4_response,raceoriginoption5_response,raceoriginoption6_response,raceoriginoption7_response,raceoriginoption8_response,raceoriginoption9_response,raceoriginoption10_response,raceoriginoption11_response,raceoriginoption12_response,raceoriginoption13_response,raceoriginother_response,highest_level_of_education_response,highest_level_of_educationother_response,year_in_College_response,major_response,household_education_response,homeownership_response,rooms_in_house_response,region_of_us_response,region_of_usother_response
0,23140554,2,Female,NaN,21,"Hispanic or Latino (a person of Cuban, Mexican...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,"Some college, no degree",NaN,Four Years,Humanities / Arts,Four Year Degree,yes,9,"Pacific (Washington, Oregon, California, Alask...",NaN
1,664692613,1,Female,NaN,18,Not Hispanic or Latino),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,"Some college, no degree",NaN,First Year,Social Science,Some Graduate School,yes,11+,"New England (Maine, New Hampshire, Vermont, Ma...",NaN
2,599191245,2,Gender Variant/Non-Conforming,NaN,21,Not Hispanic or Latino),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,"Some college, no degree",NaN,Third Year,Social Science,Four Year Degree,no,6,"New England (Maine, New Hampshire, Vermont, Ma...",NaN
3,481626968,2,Male,NaN,21,Not Hispanic or Latino),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,"Some college, no degree",NaN,Third Year,Chemistry / Biochemistry,Four Year Degree,no,5,"Middle Atlantic (New York, New Jersey, Pennsyl...",NaN
4,299228195,2,Female,NaN,18,Not Hispanic or Latino),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,"Some college, no degree",NaN,First Year,Social Science,Master's Degree,no,11+,"New England (Maine, New Hampshire, Vermont, Ma...",NaN
5,464449427,1,Female,NaN,18,I prefer not to answer this question,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I prefer not to answer this question,NaN,NaN,"Some college, no degree",NaN,First Year,Chemical Engineering,Master's Degree,yes,11+,"New England (Maine, New Hampshire, Vermont, Ma...",NaN
6,828122693,1,Male,NaN,20,Not Hispanic or Latino),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Middle Eastern or North African,White,NaN,NaN,NaN,"Some college, no degree",NaN,Third Year,Biology / Biotechnology,Some High School,yes,10,"New England (Maine, New Hampshire, Vermont, Ma...",NaN
7,835352491,2,Male,NaN,21,Not Hispanic or Latino),NaN,NaN,NaN,NaN,West Asian,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,"Some college, no degree",NaN,Third Year,Other (please specify):,Four Year Degree,yes,9,"New England (Maine, New Hampshire, Vermont, Ma...",NaN
8,956226984,1,Female,NaN,18,Not Hispanic or Latino),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,High school diploma or equivalent,NaN,First Year,Social Science,Four Year Degree,yes,3,"New England (Maine, New Hampshire, Vermont, Ma...",NaN
9,325562366,1,Male,NaN,21,"Hispanic or Latino (a person of Cuban, Mexican...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,"Some college, no degree",NaN,Four Years,Mechanical / Materials Engineering,Four Year Degree,yes,3,I lived outside the United States (please spec...,Dominican Republic

This data has been sorted and is ready to be merged in SPSS